Misc
Pixeval/Pixeval pull request #336
Opened 2023-11-02 15:02 UTC by Poker-sang

2023-11-13 01:02 UTC, dylech30th commented on src/Pixeval/Download/DownloadManager.cs
类似没法直接从局部的上下文获得变量类型的地方还是最好不要用匿名new？

2023-11-13 01:03 UTC, dylech30th commented on src/Pixeval/Pages/Download/DownloadListPage.xaml.cs
感觉这里这个`GetIllustrationFromIdAsync`的设计要重新考虑一下，有点害怕下载内容多的时候请求API太频繁

2023-11-15 02:19 UTC, dylech30th commented on src/Pixeval.Controls/ZoomableImage/ZoomableImage.xaml.cs
> +                    zoomableImage.SetPosition(zoomableImage.InitPosition, new(imageWidth, imageHeight));
这个地方的new最好也用target-typed的？

2023-11-15 02:21 UTC, Poker-sang commented on src/Pixeval.Controls/ZoomableImage/ZoomableImage.xaml.cs
> +                    zoomableImage.SetPosition(zoomableImage.InitPosition, new(imageWidth, imageHeight));
最后写完了用r#格式化一下

2023-11-26 09:47 UTC, dylech30th commented on src/Pixeval.Controls/AdvancedItemsView/ItemsViewLayoutType.cs
> +namespace Pixeval.Controls;
命名空间改一下

2023-11-30 01:08 UTC, dylech30th commented on src/Pixeval.Utilities/Result.cs
> +    public static Result<TNew?> Cast<TOld, TNew>(this Result<TOld> result) where TNew : class
语义错误，这里的cast不应该是`Result<TNew?>`而是`Result<TNew>`，cast失败返回`Result.Failure`

2023-11-30 01:13 UTC, dylech30th commented on src/Pixeval/Controls/IllustrationView/IllustrationViewDataProvider.cs
>          IllustrationSourceRef = new(new(new IllustrationFetchEngineIncrementalSource(FetchEngine!, limit)), this);
最好是不要这么连着三个匿名new....这种地方，从上下文看不出类型的时候最好还是显式new

2023-11-30 01:19 UTC, dylech30th requested changes
check the comment

2023-12-02 12:21 UTC, dylech30th approved these changes

2023-12-02 12:22 UTC, merged